CREATE TABLE IF NOT EXISTS WISHLIST(
WISHLIST_ID bigint PRIMARY KEY AUTO_INCREMENT COMMENT "Id for wishlist",
WISHLIST_NAME VARCHAR(255) UNIQUE NOT NULL COMMENT "NAME OF THE WISHLIST",
USER_ID bigint NOT NULL COMMENT "user id to differentiate between users",
PRODUCT_ID bigint NOT NULL COMMENT "product id which all are added",
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_DESCRIPTION(PRODUCT_ID)
);