CREATE TABLE IF NOT EXISTS product(
PRODUCT_ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
TITLE VARCHAR(255) NOT NULL COMMENT 'product title',
BRAND VARCHAR(255) NOT NULL COMMENT 'product brand',
CATEGORY VARCHAR(255) NOT NULL COMMENT 'product category',
PRICE bigint NOT NULL COMMENT 'product price',
STOCK bigint NOT NULL COMMENT 'product stock',
DISCOUNT VARCHAR(255) NOT NULL COMMENT 'product discount percentage',
RATING VARCHAR(255) NOT NULL COMMENT 'product rating',
DESCRIPTION VARCHAR(255) NOT NULL COMMENT 'product description',
IMAGE VARCHAR(255) NOT NULL COMMENT 'product image'
);